### ISSUE TITLE
Subregion API support for 2560x1080?

### ISSUE THREAD

**Issue by codsane** [paularcoleo/fortroute-mapper#1]
I was looking to play around with fortroute for a personal project, but unfortunately there doesn't seem to be any support for 2560x1080. Unfortunately you can't change fullscreen resolution in Fortnite (and due to black bars or stretching, that wouldn't work with the screen capture).

Are there any plans to open source the subregion API? I'd love to add support for 21:9 without writing my own region detection if possible.

Thank you!

**Comment by paularcoleo** [comment]
Sorry I never got around to answering this. As you might have noticed, this project has fallen out of maintenance. My interest in the game dwindled pretty significantly, and the increase in frequency of changes to the map made keeping the source map up-to-date a pain in the butt. 

The subregion API was just a database lookup to a small flask app I'd set up, so that I could add support for new resolutions without making people pull the repo again. The highest resolution my monitors support is 1920x1080, hence why that is the largest option. To determine the subregion, I would just take a screen shot in game, and then use the Rulers in Photoshop to figure out the upper-left (x1, y1) and lower-right (x2, y2) bounds of the minimap. If you still want to make this work for your machine, I would just modify get_minimap_subregion method in the SubregionManager class and have it return a hard-coded value for that resolution (e.g. `[x1, y1, x2, y2]`), rather than have it look up the values in the API (which may not last very long into the future).

Best of luck!
